# Generated by Django 3.0.7 on 2020-09-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_cost', models.IntegerField()),
                ('p_wight', models.IntegerField()),
                ('p_type', models.CharField(choices=[('Fashion', 'fashion'), ('Electronics', 'electronics'), ('Home', 'home')], max_length=30)),
                ('p_date', models.DateField()),
            ],
        ),
    ]
