# Generated by Django 3.0.7 on 2020-09-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_data',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emp_data',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='emp_data',
            name='desig',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='emp_data',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='emp_data',
            name='salary',
            field=models.FloatField(null=True),
        ),
    ]
